services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binary-analysis
    image: agentic-binary-analysis:dev

    volumes:
      - .:/app
      - ./samples:/samples:ro   

    working_dir: /app
    tty: true
    stdin_open: true

    environment:
      PYTHONUNBUFFERED: "1"

    command: bash
